#ifndef PLATFORM_SW_APP_PLATFORM_CONFIG_H_
#define PLATFORM_SW_APP_PLATFORM_CONFIG_H_

#ifndef PLATFORM_CLOCK_HZ
#define PLATFORM_CLOCK_HZ 50000000u
#endif

#ifndef PLATFORM_UART_BASE
#define PLATFORM_UART_BASE 0x40005000u
#endif

#ifndef PLATFORM_UART_RX_OFFSET
#define PLATFORM_UART_RX_OFFSET 0x00u
#endif

#ifndef PLATFORM_UART_TX_OFFSET
#define PLATFORM_UART_TX_OFFSET 0x04u
#endif

#ifndef PLATFORM_UART_STATUS_OFFSET
#define PLATFORM_UART_STATUS_OFFSET 0x08u
#endif

#ifndef PLATFORM_UART_RX_READY_MASK
#define PLATFORM_UART_RX_READY_MASK 0x01u
#endif

#ifndef PLATFORM_UART_TX_FULL_MASK
#define PLATFORM_UART_TX_FULL_MASK 0x08u
#endif

#ifndef PLATFORM_REBOOT_DELAY_LOOPS
#define PLATFORM_REBOOT_DELAY_LOOPS 50000u
#endif

#ifndef PLATFORM_DEFAULT_TENSOR_ARENA_SIZE
#define PLATFORM_DEFAULT_TENSOR_ARENA_SIZE (256u * 1024u)
#endif

#ifndef CBO_BLOCK_BYTES
#define CBO_BLOCK_BYTES 64u
#endif

#ifndef MODEL_TOLERANCE
#define MODEL_TOLERANCE 2
#endif

#ifndef NPU_TEST_MEMORY_BYTES
#define NPU_TEST_MEMORY_BYTES 65536u
#endif

#ifndef NPU_TEST_MEMORY_ALIGN
#define NPU_TEST_MEMORY_ALIGN 16384u
#endif

#ifndef NPU_TEST_FUNCTIONAL_OFFSET
#define NPU_TEST_FUNCTIONAL_OFFSET 0x2000u
#endif

#ifndef NPU_TEST_STRESS_OFFSET
#define NPU_TEST_STRESS_OFFSET 0x3000u
#endif

#ifndef NPU_STRESS_LOOPS
#define NPU_STRESS_LOOPS 10000u
#endif

#ifndef NPU_STRESS_PROGRESS_INTERVAL
#define NPU_STRESS_PROGRESS_INTERVAL 2500u
#endif

#endif  // PLATFORM_SW_APP_PLATFORM_CONFIG_H_
