#ifndef PLATFORM_SW_APP_PLATFORM_CONFIG_H_
#define PLATFORM_SW_APP_PLATFORM_CONFIG_H_

#ifndef PLATFORM_CLOCK_HZ
#define PLATFORM_CLOCK_HZ 70000000u
#endif

#ifndef PLATFORM_UART_BASE
#define PLATFORM_UART_BASE 0x40005000u
#endif

#ifndef PLATFORM_UART_RX_OFFSET
#define PLATFORM_UART_RX_OFFSET 0x00u
#endif

#ifndef PLATFORM_UART_TX_OFFSET
#define PLATFORM_UART_TX_OFFSET 0x04u
#endif

#ifndef PLATFORM_UART_STATUS_OFFSET
#define PLATFORM_UART_STATUS_OFFSET 0x08u
#endif

#ifndef PLATFORM_UART_RX_READY_MASK
#define PLATFORM_UART_RX_READY_MASK 0x01u
#endif

#ifndef PLATFORM_UART_TX_FULL_MASK
#define PLATFORM_UART_TX_FULL_MASK 0x08u
#endif

#ifndef PLATFORM_REBOOT_DELAY_LOOPS
#define PLATFORM_REBOOT_DELAY_LOOPS 50000u
#endif

#ifndef PLATFORM_DEFAULT_TENSOR_ARENA_SIZE
#define PLATFORM_DEFAULT_TENSOR_ARENA_SIZE (256u * 1024u)
#endif

#ifndef MODEL_TOLERANCE
#define MODEL_TOLERANCE 0
#endif

#ifndef ACCEL_TEST_MEMORY_BYTES
#ifdef NPU_TEST_MEMORY_BYTES
#define ACCEL_TEST_MEMORY_BYTES NPU_TEST_MEMORY_BYTES
#else
#define ACCEL_TEST_MEMORY_BYTES 65536u
#endif
#endif

#ifndef ACCEL_TEST_MEMORY_ALIGN
#ifdef NPU_TEST_MEMORY_ALIGN
#define ACCEL_TEST_MEMORY_ALIGN NPU_TEST_MEMORY_ALIGN
#else
#define ACCEL_TEST_MEMORY_ALIGN 16384u
#endif
#endif

#ifndef ACCEL_TEST_FUNCTIONAL_OFFSET
#ifdef NPU_TEST_FUNCTIONAL_OFFSET
#define ACCEL_TEST_FUNCTIONAL_OFFSET NPU_TEST_FUNCTIONAL_OFFSET
#else
#define ACCEL_TEST_FUNCTIONAL_OFFSET 0x2000u
#endif
#endif

#ifndef ACCEL_TEST_STRESS_OFFSET
#ifdef NPU_TEST_STRESS_OFFSET
#define ACCEL_TEST_STRESS_OFFSET NPU_TEST_STRESS_OFFSET
#else
#define ACCEL_TEST_STRESS_OFFSET 0x3000u
#endif
#endif

#ifndef ACCEL_STRESS_LOOPS
#ifdef NPU_STRESS_LOOPS
#define ACCEL_STRESS_LOOPS NPU_STRESS_LOOPS
#else
#define ACCEL_STRESS_LOOPS 10000u
#endif
#endif

#ifndef ACCEL_BENCH_LOOPS
#ifdef NPU_BENCH_LOOPS
#define ACCEL_BENCH_LOOPS NPU_BENCH_LOOPS
#else
#define ACCEL_BENCH_LOOPS 10000u
#endif
#endif

#ifndef ACCEL_STRESS_PROGRESS_INTERVAL
#ifdef NPU_STRESS_PROGRESS_INTERVAL
#define ACCEL_STRESS_PROGRESS_INTERVAL NPU_STRESS_PROGRESS_INTERVAL
#else
#define ACCEL_STRESS_PROGRESS_INTERVAL 2500u
#endif
#endif

#ifndef NPU_TEST_MEMORY_BYTES
#define NPU_TEST_MEMORY_BYTES ACCEL_TEST_MEMORY_BYTES
#endif

#ifndef NPU_TEST_MEMORY_ALIGN
#define NPU_TEST_MEMORY_ALIGN ACCEL_TEST_MEMORY_ALIGN
#endif

#ifndef NPU_TEST_FUNCTIONAL_OFFSET
#define NPU_TEST_FUNCTIONAL_OFFSET ACCEL_TEST_FUNCTIONAL_OFFSET
#endif

#ifndef NPU_TEST_STRESS_OFFSET
#define NPU_TEST_STRESS_OFFSET ACCEL_TEST_STRESS_OFFSET
#endif

#ifndef NPU_STRESS_LOOPS
#define NPU_STRESS_LOOPS ACCEL_STRESS_LOOPS
#endif

#ifndef NPU_BENCH_LOOPS
#define NPU_BENCH_LOOPS ACCEL_BENCH_LOOPS
#endif

#ifndef NPU_STRESS_PROGRESS_INTERVAL
#define NPU_STRESS_PROGRESS_INTERVAL ACCEL_STRESS_PROGRESS_INTERVAL
#endif

#endif  // PLATFORM_SW_APP_PLATFORM_CONFIG_H_
